import type { InferInsertModel, InferSelectModel } from "drizzle-orm";
import { dictionaryEntries } from "./dictionary.js";
import { grammarPatterns } from "./grammar.js";
import { kanjiEntries } from "./kanji.js";
import { mediaAssets } from "./media.js";
import { dictionaryEntryLinks, dictionaryGrammarLinks, dictionaryKanjiLinks, grammarPatternLinks, kanjiEntryLinks, questionGrammarLinks, questionVocabularyLinks, sentenceGrammarLinks, sentenceVocabularyLinks } from "./relations.js";
import { sentences } from "./sentences.js";
import { srsCards, srsDecks, srsReviewLogs } from "./srs.js";
import { practiceTests, questions, testSessions } from "./tests.js";
import { userBookmarks, userProgress, users } from "./users.js";
export * from "./dictionary.js";
export * from "./enums.js";
export * from "./grammar.js";
export * from "./kanji.js";
export * from "./media.js";
export * from "./relations.js";
export * from "./sentences.js";
export * from "./srs.js";
export * from "./tests.js";
export * from "./types.js";
export * from "./users.js";
export type DictionaryEntry = InferSelectModel<typeof dictionaryEntries>;
export type NewDictionaryEntry = InferInsertModel<typeof dictionaryEntries>;
export type KanjiEntry = InferSelectModel<typeof kanjiEntries>;
export type NewKanjiEntry = InferInsertModel<typeof kanjiEntries>;
export type GrammarPattern = InferSelectModel<typeof grammarPatterns>;
export type NewGrammarPattern = InferInsertModel<typeof grammarPatterns>;
export type Sentence = InferSelectModel<typeof sentences>;
export type NewSentence = InferInsertModel<typeof sentences>;
export type User = InferSelectModel<typeof users>;
export type NewUser = InferInsertModel<typeof users>;
export type UserProgress = InferSelectModel<typeof userProgress>;
export type NewUserProgress = InferInsertModel<typeof userProgress>;
export type UserBookmark = InferSelectModel<typeof userBookmarks>;
export type NewUserBookmark = InferInsertModel<typeof userBookmarks>;
export type PracticeTest = InferSelectModel<typeof practiceTests>;
export type NewPracticeTest = InferInsertModel<typeof practiceTests>;
export type Question = InferSelectModel<typeof questions>;
export type NewQuestion = InferInsertModel<typeof questions>;
export type TestSession = InferSelectModel<typeof testSessions>;
export type NewTestSession = InferInsertModel<typeof testSessions>;
export type SrsDeck = InferSelectModel<typeof srsDecks>;
export type NewSrsDeck = InferInsertModel<typeof srsDecks>;
export type SrsCard = InferSelectModel<typeof srsCards>;
export type NewSrsCard = InferInsertModel<typeof srsCards>;
export type SrsReviewLog = InferSelectModel<typeof srsReviewLogs>;
export type NewSrsReviewLog = InferInsertModel<typeof srsReviewLogs>;
export type MediaAsset = InferSelectModel<typeof mediaAssets>;
export type NewMediaAsset = InferInsertModel<typeof mediaAssets>;
export type DictionaryEntryLink = InferSelectModel<typeof dictionaryEntryLinks>;
export type NewDictionaryEntryLink = InferInsertModel<typeof dictionaryEntryLinks>;
export type SentenceVocabularyLink = InferSelectModel<typeof sentenceVocabularyLinks>;
export type NewSentenceVocabularyLink = InferInsertModel<typeof sentenceVocabularyLinks>;
export type SentenceGrammarLink = InferSelectModel<typeof sentenceGrammarLinks>;
export type NewSentenceGrammarLink = InferInsertModel<typeof sentenceGrammarLinks>;
export type DictionaryGrammarLink = InferSelectModel<typeof dictionaryGrammarLinks>;
export type NewDictionaryGrammarLink = InferInsertModel<typeof dictionaryGrammarLinks>;
export type DictionaryKanjiLink = InferSelectModel<typeof dictionaryKanjiLinks>;
export type NewDictionaryKanjiLink = InferInsertModel<typeof dictionaryKanjiLinks>;
export type GrammarPatternLink = InferSelectModel<typeof grammarPatternLinks>;
export type NewGrammarPatternLink = InferInsertModel<typeof grammarPatternLinks>;
export type KanjiEntryLink = InferSelectModel<typeof kanjiEntryLinks>;
export type NewKanjiEntryLink = InferInsertModel<typeof kanjiEntryLinks>;
export type QuestionVocabularyLink = InferSelectModel<typeof questionVocabularyLinks>;
export type NewQuestionVocabularyLink = InferInsertModel<typeof questionVocabularyLinks>;
export type QuestionGrammarLink = InferSelectModel<typeof questionGrammarLinks>;
export type NewQuestionGrammarLink = InferInsertModel<typeof questionGrammarLinks>;
//# sourceMappingURL=index.d.ts.map