import type {
  DictionaryAutocompleteItem,
  DictionaryDetailData,
  DictionaryEntryData,
  KanjiDetailData,
  SrsReviewContent,
} from "@/types/content";

const ids = {
  taberu: "00000000-0000-4000-8000-000000000001",
  nomu: "00000000-0000-4000-8000-000000000002",
  mizuWord: "00000000-0000-4000-8000-000000000003",
  gakusei: "00000000-0000-4000-8000-000000000004",
  nihon: "00000000-0000-4000-8000-000000000005",
  mizuKanji: "00000000-0000-4000-8000-000000001003",
};

export const demoDictionaryEntries: DictionaryEntryData[] = [
  {
    id: ids.taberu,
    word: "食べる",
    kana: "たべる",
    romaji: "taberu",
    furigana: [{ base: "食", ruby: "た" }, { base: "べる", ruby: "" }],
    meanings: [
      { lang: "en", value: "to eat", pos: "verb (ichidan)" },
      { lang: "en", value: "to live on; to make a living from", pos: "verb" },
    ],
    jlpt_level: "N5",
    part_of_speech: ["Verb", "Group 2"],
    pitch_accent: null,
    frequency_rank: 530,
    kanji_ids: ["食"],
    audio_url: null,
    tags: ["food", "daily-life"],
    source: "custom",
  },
  {
    id: ids.nomu,
    word: "飲む",
    kana: "のむ",
    romaji: "nomu",
    furigana: [{ base: "飲", ruby: "の" }, { base: "む", ruby: "" }],
    meanings: [{ lang: "en", value: "to drink", pos: "verb (godan)" }],
    jlpt_level: "N5",
    part_of_speech: ["Verb", "Group 1"],
    pitch_accent: null,
    frequency_rank: 820,
    kanji_ids: ["飲"],
    audio_url: "/demo/audio/nomu.mp3",
    tags: ["food", "daily-life"],
    source: "custom",
  },
  {
    id: ids.mizuWord,
    word: "水",
    kana: "みず",
    romaji: "mizu",
    furigana: [{ base: "水", ruby: "みず" }],
    meanings: [{ lang: "en", value: "water", pos: "noun" }],
    jlpt_level: "N5",
    part_of_speech: ["Noun"],
    pitch_accent: null,
    frequency_rank: 310,
    kanji_ids: ["水"],
    audio_url: null,
    tags: ["nature", "daily-life"],
    source: "custom",
  },
  {
    id: ids.gakusei,
    word: "学生",
    kana: "がくせい",
    romaji: "gakusei",
    furigana: [{ base: "学", ruby: "がく" }, { base: "生", ruby: "せい" }],
    meanings: [{ lang: "en", value: "student", pos: "noun" }],
    jlpt_level: "N5",
    part_of_speech: ["Noun"],
    pitch_accent: null,
    frequency_rank: 690,
    kanji_ids: ["学", "生"],
    audio_url: null,
    tags: ["school", "people"],
    source: "custom",
  },
  {
    id: ids.nihon,
    word: "日本",
    kana: "にほん",
    romaji: "nihon",
    furigana: [{ base: "日", ruby: "に" }, { base: "本", ruby: "ほん" }],
    meanings: [{ lang: "en", value: "Japan", pos: "proper noun" }],
    jlpt_level: "N5",
    part_of_speech: ["Proper noun"],
    pitch_accent: null,
    frequency_rank: 40,
    kanji_ids: ["日", "本"],
    audio_url: null,
    tags: ["place"],
    source: "custom",
  },
];

export const demoDictionaryDetail: DictionaryDetailData = {
  ...demoDictionaryEntries[0]!,
  example_sentences: [
    {
      id: "sentence-demo-1",
      japanese: "毎日ご飯を食べます。",
      furigana_html:
        "<ruby>毎日<rt>まいにち</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>を<ruby>食<rt>た</rt></ruby>べます。",
      translations: [{ lang: "en", value: "I eat rice every day." }],
      audio_url: null,
      jlpt_level: "N5",
      tags: ["daily-life"],
    },
    {
      id: "sentence-demo-2",
      japanese: "朝ご飯を食べてから、学校へ行きます。",
      furigana_html:
        "<ruby>朝<rt>あさ</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>を<ruby>食<rt>た</rt></ruby>べてから、<ruby>学校<rt>がっこう</rt></ruby>へ<ruby>行<rt>い</rt></ruby>きます。",
      translations: [{ lang: "en", value: "After breakfast, I go to school." }],
      audio_url: null,
      jlpt_level: "N5",
      tags: ["school"],
    },
  ],
  related_kanji: [
    {
      id: "00000000-0000-4000-8000-000000001004",
      character: "食",
      unicode: "U+98DF",
      onyomi: ["ショク"],
      kunyomi: ["た.べる"],
      meanings: [{ lang: "en", value: "eat; food" }],
      jlpt_level: "N5",
      grade: 2,
      frequency_rank: 328,
      stroke_count: 9,
      radicals: ["食"],
      components: ["人", "良"],
      svg_animation_url: null,
      stroke_order_url: null,
      similar_kanji: [],
      lookalikes: [],
      mnemonics: [],
      source: "kanjidic2",
    },
  ],
  grammar_patterns: [
    {
      id: "00000000-0000-4000-8000-000000002003",
      pattern: "〜てから",
      meaning: [{ lang: "en", value: "after doing" }],
      formation: "Verb て-form + から",
      jlpt_level: "N5",
      audio_url: null,
    },
  ],
};

const mizuWords = [
  demoDictionaryEntries[2]!,
  {
    ...demoDictionaryEntries[2]!,
    id: "word-suidou",
    word: "水道",
    kana: "すいどう",
    romaji: "suidou",
    meanings: [{ lang: "en", value: "waterworks; tap water", pos: "noun" }],
  },
  {
    ...demoDictionaryEntries[2]!,
    id: "word-suiyoubi",
    word: "水曜日",
    kana: "すいようび",
    romaji: "suiyoubi",
    meanings: [{ lang: "en", value: "Wednesday", pos: "noun" }],
  },
];

export const demoKanjiDetail: KanjiDetailData = {
  id: ids.mizuKanji,
  character: "水",
  unicode: "U+6C34",
  onyomi: ["スイ"],
  kunyomi: ["みず"],
  meanings: [{ lang: "en", value: "water" }],
  jlpt_level: "N5",
  grade: 1,
  frequency_rank: 223,
  stroke_count: 4,
  radicals: ["水"],
  components: ["水"],
  svg_animation_url: null,
  stroke_order_url: null,
  similar_kanji: ["氷", "永"],
  lookalikes: ["木"],
  mnemonics: [{ source: "custom", text: "A central stream with drops flowing on both sides." }],
  source: "kanjidic2",
  example_words: mizuWords,
  similar_kanji_details: [],
};

export const demoWaterStrokePaths = [
  "M57 12 C56 28 55 47 55 82",
  "M22 36 C31 39 37 43 43 49",
  "M49 44 C42 57 33 67 20 74",
  "M61 43 C70 56 80 66 91 72",
];

export const demoAutocomplete: DictionaryAutocompleteItem[] = demoDictionaryEntries.map((entry) => ({
  id: entry.id,
  word: entry.word,
  kana: entry.kana,
  meaning: entry.meanings[0]?.value ?? null,
  jlpt_level: entry.jlpt_level,
}));

export const demoSrsCards: SrsReviewContent[] = [
  {
    id: "srs-1",
    itemType: "word",
    front: "食べる",
    reading: "たべる",
    meanings: ["to eat", "to live on"],
    example: "毎日ご飯を食べます。",
    grammar: "Ichidan verb · polite: 食べます",
    jlptLevel: "N5",
  },
  {
    id: "srs-2",
    itemType: "kanji",
    front: "水",
    reading: "スイ・みず",
    meanings: ["water"],
    example: "水曜日・すいようび・Wednesday",
    jlptLevel: "N5",
  },
  {
    id: "srs-3",
    itemType: "grammar",
    front: "〜てから",
    meanings: ["after doing"],
    example: "朝ご飯を食べてから、学校へ行きます。",
    grammar: "Verb て-form + から",
    jlptLevel: "N5",
  },
];
